import type { Recommendation } from "./types"

export const mockRecommendation: Recommendation = {
  supplies: [
    { name: "飲料水", qty: 9, unit: "L", category: "food_water", img: "/images/food.webp", isConsumable: true },
    { name: "食事", qty: 18, unit: "食", category: "food_water", ecUrl: "https://shop.hebel-haus.com/products/detail/NET50006-00-00-00-00-50006", img: "/images/food.webp", isConsumable: true },
    { name: "お菓子", qty: 1, unit: "袋", category: "food_water", img: "/images/food.webp", isConsumable: true },
    { name: "携帯用トイレ", qty: 15, unit: "個", category: "hygiene", ecUrl: "https://shop.hebel-haus.com/products/detail/NET50010-00-00-00-00-50010", img: "/images/food.webp", isConsumable: true },
    { name: "ウェットティッシュ", qty: 3, unit: "パック", category: "hygiene", img: "/images/food.webp", isConsumable: true },
    { name: "マスク", qty: 30, unit: "枚", category: "hygiene", img: "/images/food.webp", isConsumable: true },
    { name: "消毒液", qty: 2, unit: "本", category: "hygiene", img: "/images/food.webp", isConsumable: true },
    { name: "乾電池", qty: 0, unit: "適量", category: "daily_safety", img: "/images/food.webp", isConsumable: false },
    { name: "救急セット", qty: 1, unit: "セット", category: "daily_safety", img: "/images/food.webp", isConsumable: false },
    { name: "懐中電灯", qty: 2, unit: "個", category: "daily_safety", img: "/images/food.webp", isConsumable: false },
    { name: "ポータブル電源", qty: 1, unit: "個", category: "daily_safety", ecUrl: "https://shop.hebel-haus.com/products/detail/NET51130-00-tanpin-kg12-00-51130", img: "/images/food.webp", isConsumable: false },
    { name: "ソーラーパネル", qty: 1, unit: "個", category: "daily_safety", ecUrl: "https://shop.hebel-haus.com/products/detail/NET50138-00-00-kg7-00-50138", img: "/images/food.webp", isConsumable: false },
    { name: "ラジオ", qty: 1, unit: "台", category: "daily_safety", img: "/images/food.webp", isConsumable: false },
    { name: "生理用品", qty: 1, unit: "セット", category: "women", img: "/images/food.webp", isConsumable: true },
    { name: "粉ミルク", qty: 1, unit: "缶", category: "infant", img: "/images/food.webp", isConsumable: true },
    { name: "哺乳瓶", qty: 2, unit: "本", category: "infant", img: "/images/food.webp", isConsumable: false },
    { name: "おむつ", qty: 30, unit: "枚", category: "infant", img: "/images/food.webp", isConsumable: true },
    { name: "お気に入りのおもちゃ", qty: 1, unit: "個", category: "child", img: "/images/food.webp", isConsumable: false },
    { name: "絵本・漫画", qty: 2, unit: "冊", category: "child", img: "/images/food.webp", isConsumable: false },
    { name: "常備薬", qty: 1, unit: "セット", category: "elderly", img: "/images/food.webp", isConsumable: true },
    { name: "入れ歯洗浄剤", qty: 1, unit: "箱", category: "elderly", img: "/images/food.webp", isConsumable: true },
    { name: "ペットフード", qty: 7, unit: "日分", category: "pet", img: "/images/food.webp", isConsumable: true },
  ],
  advice: [
    { id: "allergy", title: "食物アレルギー対策", content: "アレルギー対応の非常食を備蓄し、医薬品（エピペンなど）も用意しておきましょう。家族全員がアレルギーについて理解し、対応できるようにしておくことが重要です。" },
    { id: "care", title: "介護が必要な方の対策", content: "介護用品（おむつ、清拭剤など）の備蓄、服用中の薬のリスト作成、避難所での介護スペース確保の事前相談などが重要です。また、介護者自身の健康管理も忘れずに。" },
    { id: "illness", title: "持病がある方の対策", content: "最低2週間分の常備薬を用意し、お薬手帳のコピーを保管しておきましょう。医療機器が必要な場合は、停電対策も考慮してください。" },
    { id: "disability", title: "障がいがある方の対策", content: "個別の避難計画を作成し、必要な支援機器・道具を備えておきましょう。地域の支援制度を事前に確認し、避難訓練に参加することも大切です。" },
    { id: "heatSensitive", title: "暑さに弱い方の対策", content: "携帯扇風機、冷却シートを用意しましょう。水分補給用の経口補水液も備蓄しておくと安心です。" },
    { id: "coldSensitive", title: "寒さに弱い方の対策", content: "使い捨てカイロ、厚手の毛布、防寒着を備蓄しましょう。避難所は冷えることが多いので、重ね着できる衣類を用意しておくことをおすすめします。" },
    { id: "sweetTooth", title: "甘いものが好きな方の対策", content: "チョコレートやキャンディなどの保存の効く甘いものを備蓄しておくと、ストレス軽減に役立ちます。ただし、賞味期限と保管場所に注意しましょう。" },
    { id: "pickyEater", title: "食べ物の好き嫌いが多い方の対策", content: "普段から食べ慣れているものを中心に備蓄し、少しずつ食べられるよう小分けにしておくと良いでしょう。栄養補助食品も検討してください。" },
    { id: "germSensitive", title: "衛生面が気になる方の対策", content: "除菌ウェットティッシュ、ハンドソープ、マスク、使い捨て手袋などを多めに備蓄しましょう。簡易トイレ用の消臭剤も役立ちます。" },
    { id: "dislikeInsects", title: "虫が苦手な方の対策", content: "虫除けスプレー、蚊取り線香、防虫ネットなどを用意しておきましょう。避難所では窓際を避けるなどの工夫も有効です。" },
  ],
  emergencyItems: [
    { name: "飲料水", category: "food_water", priority: "high" },
    { name: "非常食", category: "food_water", priority: "high" },
    { name: "お菓子・栄養補助食品", category: "food_water", priority: "medium" },
    { name: "懐中電灯", category: "daily_safety", priority: "high" },
    { name: "乾電池", category: "daily_safety", priority: "medium" },
    { name: "ラジオ", category: "daily_safety", priority: "high" },
    { name: "救急セット", category: "daily_safety", priority: "high" },
    { name: "ライター・マッチ", category: "daily_safety", priority: "medium" },
    { name: "ロープ", category: "daily_safety", priority: "medium" },
    { name: "毛布・タオル", category: "daily_safety", priority: "medium" },
    { name: "レインコート", category: "daily_safety", priority: "medium" },
  ],
  plan: {
    title: "ファミリー安心プラン",
    description: "お子様とペットがいるご家庭向けの総合防災プランです。食料・水・医薬品から避難用品まで、必要なものをリストアップしています。",
    cta: "/sample-plan.pdf",
  },
}
